[linux]
DC-LNX01 ansible_host=10.19.110.11
DC-LNX02 ansible_host=10.19.110.12
DC-SVC01 ansible_host=10.19.110.31
DC-CL01 ansible_host=10.19.120.11
HQ-LNX01 ansible_host=10.19.20.30

[linux:vars]
ansible_user=root
ansible_ssh_common_args=-o StrictHostKeyChecking=no
